### ISSUE TITLE
Effects of priority and due date on NextAction

### ISSUE THREAD

**Issue by thomasjsn** [akramer/NextAction#7]
Hi

Is it true that it's only the sequence that is taken into account when setting the next action? The sort method seems to have been removed.

**Comment by akramer** [comment]
Yes, I removed that feature, I didn't know anyone was using it. Were you? I think I can add it back in without too much difficulty.

**Comment by HebronNor** [comment]
I just started using the tool; but could not make it behave as explained in the readme file; "Importance is determined by...". That's when I noticed that the sort method was removed.

It seems difficult to both allow for importance as marking the next action and sorting by importance. So I forked the project; removed the `--use_priority` option and re-enabled the sorting method. Along with some addition tweaks. So you don't have to do any changes on my behalf.

I'll be happy to submit the changes as a pull request, but other users might be using the priority option.
